/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProjectRouteRouteImport } from './routes/_project/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthenticatedSubscribeRouteImport } from './routes/_authenticated.subscribe'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as ApiAutumnSplatRouteImport } from './routes/api/autumn/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppHelpDataforseoApiKeyRouteImport } from './routes/_app/help/dataforseo-api-key'
import { Route as ProjectPProjectIdRouteRouteImport } from './routes/_project/p/$projectId/route'
import { Route as ProjectPProjectIdIndexRouteImport } from './routes/_project/p/$projectId/index'
import { Route as ProjectPProjectIdSavedRouteImport } from './routes/_project/p/$projectId/saved'
import { Route as ProjectPProjectIdRankTrackingRouteImport } from './routes/_project/p/$projectId/rank-tracking'
import { Route as ProjectPProjectIdPromptExplorerRouteImport } from './routes/_project/p/$projectId/prompt-explorer'
import { Route as ProjectPProjectIdKeywordsRouteImport } from './routes/_project/p/$projectId/keywords'
import { Route as ProjectPProjectIdDomainRouteImport } from './routes/_project/p/$projectId/domain'
import { Route as ProjectPProjectIdBrandLookupRouteImport } from './routes/_project/p/$projectId/brand-lookup'
import { Route as ProjectPProjectIdBacklinksRouteImport } from './routes/_project/p/$projectId/backlinks'
import { Route as ProjectPProjectIdAuditRouteImport } from './routes/_project/p/$projectId/audit'
import { Route as ProjectPProjectIdAiRouteImport } from './routes/_project/p/$projectId/ai'
import { Route as ProjectPProjectIdRankTrackingIndexRouteImport } from './routes/_project/p/$projectId/rank-tracking/index'
import { Route as ProjectPProjectIdAuditIndexRouteImport } from './routes/_project/p/$projectId/audit/index'
import { Route as ProjectPProjectIdRankTrackingConfigIdRouteImport } from './routes/_project/p/$projectId/rank-tracking/$configId'
import { Route as ProjectPProjectIdAuditIssuesResultIdRouteImport } from './routes/_project/p/$projectId/audit/issues/$resultId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/_project',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthenticatedSubscribeRoute = AuthenticatedSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAutumnSplatRoute = ApiAutumnSplatRouteImport.update({
  id: '/api/autumn/$',
  path: '/api/autumn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHelpDataforseoApiKeyRoute = AppHelpDataforseoApiKeyRouteImport.update({
  id: '/help/dataforseo-api-key',
  path: '/help/dataforseo-api-key',
  getParentRoute: () => AppRouteRoute,
} as any)
const ProjectPProjectIdRouteRoute = ProjectPProjectIdRouteRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectPProjectIdIndexRoute = ProjectPProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdSavedRoute = ProjectPProjectIdSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdRankTrackingRoute =
  ProjectPProjectIdRankTrackingRouteImport.update({
    id: '/rank-tracking',
    path: '/rank-tracking',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdPromptExplorerRoute =
  ProjectPProjectIdPromptExplorerRouteImport.update({
    id: '/prompt-explorer',
    path: '/prompt-explorer',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdKeywordsRoute =
  ProjectPProjectIdKeywordsRouteImport.update({
    id: '/keywords',
    path: '/keywords',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdDomainRoute = ProjectPProjectIdDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdBrandLookupRoute =
  ProjectPProjectIdBrandLookupRouteImport.update({
    id: '/brand-lookup',
    path: '/brand-lookup',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdBacklinksRoute =
  ProjectPProjectIdBacklinksRouteImport.update({
    id: '/backlinks',
    path: '/backlinks',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdAuditRoute = ProjectPProjectIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdAiRoute = ProjectPProjectIdAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdRankTrackingIndexRoute =
  ProjectPProjectIdRankTrackingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectPProjectIdRankTrackingRoute,
  } as any)
const ProjectPProjectIdAuditIndexRoute =
  ProjectPProjectIdAuditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectPProjectIdAuditRoute,
  } as any)
const ProjectPProjectIdRankTrackingConfigIdRoute =
  ProjectPProjectIdRankTrackingConfigIdRouteImport.update({
    id: '/$configId',
    path: '/$configId',
    getParentRoute: () => ProjectPProjectIdRankTrackingRoute,
  } as any)
const ProjectPProjectIdAuditIssuesResultIdRoute =
  ProjectPProjectIdAuditIssuesResultIdRouteImport.update({
    id: '/issues/$resultId',
    path: '/issues/$resultId',
    getParentRoute: () => ProjectPProjectIdAuditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/billing': typeof AppBillingRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/subscribe': typeof AuthenticatedSubscribeRoute
  '/p/$projectId': typeof ProjectPProjectIdRouteRouteWithChildren
  '/help/dataforseo-api-key': typeof AppHelpDataforseoApiKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/p/$projectId/ai': typeof ProjectPProjectIdAiRoute
  '/p/$projectId/audit': typeof ProjectPProjectIdAuditRouteWithChildren
  '/p/$projectId/backlinks': typeof ProjectPProjectIdBacklinksRoute
  '/p/$projectId/brand-lookup': typeof ProjectPProjectIdBrandLookupRoute
  '/p/$projectId/domain': typeof ProjectPProjectIdDomainRoute
  '/p/$projectId/keywords': typeof ProjectPProjectIdKeywordsRoute
  '/p/$projectId/prompt-explorer': typeof ProjectPProjectIdPromptExplorerRoute
  '/p/$projectId/rank-tracking': typeof ProjectPProjectIdRankTrackingRouteWithChildren
  '/p/$projectId/saved': typeof ProjectPProjectIdSavedRoute
  '/p/$projectId/': typeof ProjectPProjectIdIndexRoute
  '/p/$projectId/rank-tracking/$configId': typeof ProjectPProjectIdRankTrackingConfigIdRoute
  '/p/$projectId/audit/': typeof ProjectPProjectIdAuditIndexRoute
  '/p/$projectId/rank-tracking/': typeof ProjectPProjectIdRankTrackingIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof ProjectPProjectIdAuditIssuesResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/billing': typeof AppBillingRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/subscribe': typeof AuthenticatedSubscribeRoute
  '/help/dataforseo-api-key': typeof AppHelpDataforseoApiKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/p/$projectId/ai': typeof ProjectPProjectIdAiRoute
  '/p/$projectId/backlinks': typeof ProjectPProjectIdBacklinksRoute
  '/p/$projectId/brand-lookup': typeof ProjectPProjectIdBrandLookupRoute
  '/p/$projectId/domain': typeof ProjectPProjectIdDomainRoute
  '/p/$projectId/keywords': typeof ProjectPProjectIdKeywordsRoute
  '/p/$projectId/prompt-explorer': typeof ProjectPProjectIdPromptExplorerRoute
  '/p/$projectId/saved': typeof ProjectPProjectIdSavedRoute
  '/p/$projectId': typeof ProjectPProjectIdIndexRoute
  '/p/$projectId/rank-tracking/$configId': typeof ProjectPProjectIdRankTrackingConfigIdRoute
  '/p/$projectId/audit': typeof ProjectPProjectIdAuditIndexRoute
  '/p/$projectId/rank-tracking': typeof ProjectPProjectIdRankTrackingIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof ProjectPProjectIdAuditIssuesResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_project': typeof ProjectRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/support': typeof AppSupportRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/subscribe': typeof AuthenticatedSubscribeRoute
  '/_app/': typeof AppIndexRoute
  '/_project/p/$projectId': typeof ProjectPProjectIdRouteRouteWithChildren
  '/_app/help/dataforseo-api-key': typeof AppHelpDataforseoApiKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/_project/p/$projectId/ai': typeof ProjectPProjectIdAiRoute
  '/_project/p/$projectId/audit': typeof ProjectPProjectIdAuditRouteWithChildren
  '/_project/p/$projectId/backlinks': typeof ProjectPProjectIdBacklinksRoute
  '/_project/p/$projectId/brand-lookup': typeof ProjectPProjectIdBrandLookupRoute
  '/_project/p/$projectId/domain': typeof ProjectPProjectIdDomainRoute
  '/_project/p/$projectId/keywords': typeof ProjectPProjectIdKeywordsRoute
  '/_project/p/$projectId/prompt-explorer': typeof ProjectPProjectIdPromptExplorerRoute
  '/_project/p/$projectId/rank-tracking': typeof ProjectPProjectIdRankTrackingRouteWithChildren
  '/_project/p/$projectId/saved': typeof ProjectPProjectIdSavedRoute
  '/_project/p/$projectId/': typeof ProjectPProjectIdIndexRoute
  '/_project/p/$projectId/rank-tracking/$configId': typeof ProjectPProjectIdRankTrackingConfigIdRoute
  '/_project/p/$projectId/audit/': typeof ProjectPProjectIdAuditIndexRoute
  '/_project/p/$projectId/rank-tracking/': typeof ProjectPProjectIdRankTrackingIndexRoute
  '/_project/p/$projectId/audit/issues/$resultId': typeof ProjectPProjectIdAuditIssuesResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/billing'
    | '/settings'
    | '/support'
    | '/sign-in'
    | '/sign-up'
    | '/subscribe'
    | '/p/$projectId'
    | '/help/dataforseo-api-key'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/p/$projectId/ai'
    | '/p/$projectId/audit'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/brand-lookup'
    | '/p/$projectId/domain'
    | '/p/$projectId/keywords'
    | '/p/$projectId/prompt-explorer'
    | '/p/$projectId/rank-tracking'
    | '/p/$projectId/saved'
    | '/p/$projectId/'
    | '/p/$projectId/rank-tracking/$configId'
    | '/p/$projectId/audit/'
    | '/p/$projectId/rank-tracking/'
    | '/p/$projectId/audit/issues/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/billing'
    | '/settings'
    | '/support'
    | '/sign-in'
    | '/sign-up'
    | '/subscribe'
    | '/help/dataforseo-api-key'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/p/$projectId/ai'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/brand-lookup'
    | '/p/$projectId/domain'
    | '/p/$projectId/keywords'
    | '/p/$projectId/prompt-explorer'
    | '/p/$projectId/saved'
    | '/p/$projectId'
    | '/p/$projectId/rank-tracking/$configId'
    | '/p/$projectId/audit'
    | '/p/$projectId/rank-tracking'
    | '/p/$projectId/audit/issues/$resultId'
  id:
    | '__root__'
    | '/_app'
    | '/_project'
    | '/_auth'
    | '/_authenticated'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/_app/billing'
    | '/_app/settings'
    | '/_app/support'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/subscribe'
    | '/_app/'
    | '/_project/p/$projectId'
    | '/_app/help/dataforseo-api-key'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/_project/p/$projectId/ai'
    | '/_project/p/$projectId/audit'
    | '/_project/p/$projectId/backlinks'
    | '/_project/p/$projectId/brand-lookup'
    | '/_project/p/$projectId/domain'
    | '/_project/p/$projectId/keywords'
    | '/_project/p/$projectId/prompt-explorer'
    | '/_project/p/$projectId/rank-tracking'
    | '/_project/p/$projectId/saved'
    | '/_project/p/$projectId/'
    | '/_project/p/$projectId/rank-tracking/$configId'
    | '/_project/p/$projectId/audit/'
    | '/_project/p/$projectId/rank-tracking/'
    | '/_project/p/$projectId/audit/issues/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAutumnSplatRoute: typeof ApiAutumnSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project': {
      id: '/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authenticated/subscribe': {
      id: '/_authenticated/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof AuthenticatedSubscribeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/autumn/$': {
      id: '/api/autumn/$'
      path: '/api/autumn/$'
      fullPath: '/api/autumn/$'
      preLoaderRoute: typeof ApiAutumnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/help/dataforseo-api-key': {
      id: '/_app/help/dataforseo-api-key'
      path: '/help/dataforseo-api-key'
      fullPath: '/help/dataforseo-api-key'
      preLoaderRoute: typeof AppHelpDataforseoApiKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_project/p/$projectId': {
      id: '/_project/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof ProjectPProjectIdRouteRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/p/$projectId/': {
      id: '/_project/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof ProjectPProjectIdIndexRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/saved': {
      id: '/_project/p/$projectId/saved'
      path: '/saved'
      fullPath: '/p/$projectId/saved'
      preLoaderRoute: typeof ProjectPProjectIdSavedRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/rank-tracking': {
      id: '/_project/p/$projectId/rank-tracking'
      path: '/rank-tracking'
      fullPath: '/p/$projectId/rank-tracking'
      preLoaderRoute: typeof ProjectPProjectIdRankTrackingRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/prompt-explorer': {
      id: '/_project/p/$projectId/prompt-explorer'
      path: '/prompt-explorer'
      fullPath: '/p/$projectId/prompt-explorer'
      preLoaderRoute: typeof ProjectPProjectIdPromptExplorerRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/keywords': {
      id: '/_project/p/$projectId/keywords'
      path: '/keywords'
      fullPath: '/p/$projectId/keywords'
      preLoaderRoute: typeof ProjectPProjectIdKeywordsRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/domain': {
      id: '/_project/p/$projectId/domain'
      path: '/domain'
      fullPath: '/p/$projectId/domain'
      preLoaderRoute: typeof ProjectPProjectIdDomainRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/brand-lookup': {
      id: '/_project/p/$projectId/brand-lookup'
      path: '/brand-lookup'
      fullPath: '/p/$projectId/brand-lookup'
      preLoaderRoute: typeof ProjectPProjectIdBrandLookupRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/backlinks': {
      id: '/_project/p/$projectId/backlinks'
      path: '/backlinks'
      fullPath: '/p/$projectId/backlinks'
      preLoaderRoute: typeof ProjectPProjectIdBacklinksRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/audit': {
      id: '/_project/p/$projectId/audit'
      path: '/audit'
      fullPath: '/p/$projectId/audit'
      preLoaderRoute: typeof ProjectPProjectIdAuditRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/ai': {
      id: '/_project/p/$projectId/ai'
      path: '/ai'
      fullPath: '/p/$projectId/ai'
      preLoaderRoute: typeof ProjectPProjectIdAiRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/rank-tracking/': {
      id: '/_project/p/$projectId/rank-tracking/'
      path: '/'
      fullPath: '/p/$projectId/rank-tracking/'
      preLoaderRoute: typeof ProjectPProjectIdRankTrackingIndexRouteImport
      parentRoute: typeof ProjectPProjectIdRankTrackingRoute
    }
    '/_project/p/$projectId/audit/': {
      id: '/_project/p/$projectId/audit/'
      path: '/'
      fullPath: '/p/$projectId/audit/'
      preLoaderRoute: typeof ProjectPProjectIdAuditIndexRouteImport
      parentRoute: typeof ProjectPProjectIdAuditRoute
    }
    '/_project/p/$projectId/rank-tracking/$configId': {
      id: '/_project/p/$projectId/rank-tracking/$configId'
      path: '/$configId'
      fullPath: '/p/$projectId/rank-tracking/$configId'
      preLoaderRoute: typeof ProjectPProjectIdRankTrackingConfigIdRouteImport
      parentRoute: typeof ProjectPProjectIdRankTrackingRoute
    }
    '/_project/p/$projectId/audit/issues/$resultId': {
      id: '/_project/p/$projectId/audit/issues/$resultId'
      path: '/issues/$resultId'
      fullPath: '/p/$projectId/audit/issues/$resultId'
      preLoaderRoute: typeof ProjectPProjectIdAuditIssuesResultIdRouteImport
      parentRoute: typeof ProjectPProjectIdAuditRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHelpDataforseoApiKeyRoute: typeof AppHelpDataforseoApiKeyRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
  AppHelpDataforseoApiKeyRoute: AppHelpDataforseoApiKeyRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ProjectPProjectIdAuditRouteChildren {
  ProjectPProjectIdAuditIndexRoute: typeof ProjectPProjectIdAuditIndexRoute
  ProjectPProjectIdAuditIssuesResultIdRoute: typeof ProjectPProjectIdAuditIssuesResultIdRoute
}

const ProjectPProjectIdAuditRouteChildren: ProjectPProjectIdAuditRouteChildren =
  {
    ProjectPProjectIdAuditIndexRoute: ProjectPProjectIdAuditIndexRoute,
    ProjectPProjectIdAuditIssuesResultIdRoute:
      ProjectPProjectIdAuditIssuesResultIdRoute,
  }

const ProjectPProjectIdAuditRouteWithChildren =
  ProjectPProjectIdAuditRoute._addFileChildren(
    ProjectPProjectIdAuditRouteChildren,
  )

interface ProjectPProjectIdRankTrackingRouteChildren {
  ProjectPProjectIdRankTrackingConfigIdRoute: typeof ProjectPProjectIdRankTrackingConfigIdRoute
  ProjectPProjectIdRankTrackingIndexRoute: typeof ProjectPProjectIdRankTrackingIndexRoute
}

const ProjectPProjectIdRankTrackingRouteChildren: ProjectPProjectIdRankTrackingRouteChildren =
  {
    ProjectPProjectIdRankTrackingConfigIdRoute:
      ProjectPProjectIdRankTrackingConfigIdRoute,
    ProjectPProjectIdRankTrackingIndexRoute:
      ProjectPProjectIdRankTrackingIndexRoute,
  }

const ProjectPProjectIdRankTrackingRouteWithChildren =
  ProjectPProjectIdRankTrackingRoute._addFileChildren(
    ProjectPProjectIdRankTrackingRouteChildren,
  )

interface ProjectPProjectIdRouteRouteChildren {
  ProjectPProjectIdAiRoute: typeof ProjectPProjectIdAiRoute
  ProjectPProjectIdAuditRoute: typeof ProjectPProjectIdAuditRouteWithChildren
  ProjectPProjectIdBacklinksRoute: typeof ProjectPProjectIdBacklinksRoute
  ProjectPProjectIdBrandLookupRoute: typeof ProjectPProjectIdBrandLookupRoute
  ProjectPProjectIdDomainRoute: typeof ProjectPProjectIdDomainRoute
  ProjectPProjectIdKeywordsRoute: typeof ProjectPProjectIdKeywordsRoute
  ProjectPProjectIdPromptExplorerRoute: typeof ProjectPProjectIdPromptExplorerRoute
  ProjectPProjectIdRankTrackingRoute: typeof ProjectPProjectIdRankTrackingRouteWithChildren
  ProjectPProjectIdSavedRoute: typeof ProjectPProjectIdSavedRoute
  ProjectPProjectIdIndexRoute: typeof ProjectPProjectIdIndexRoute
}

const ProjectPProjectIdRouteRouteChildren: ProjectPProjectIdRouteRouteChildren =
  {
    ProjectPProjectIdAiRoute: ProjectPProjectIdAiRoute,
    ProjectPProjectIdAuditRoute: ProjectPProjectIdAuditRouteWithChildren,
    ProjectPProjectIdBacklinksRoute: ProjectPProjectIdBacklinksRoute,
    ProjectPProjectIdBrandLookupRoute: ProjectPProjectIdBrandLookupRoute,
    ProjectPProjectIdDomainRoute: ProjectPProjectIdDomainRoute,
    ProjectPProjectIdKeywordsRoute: ProjectPProjectIdKeywordsRoute,
    ProjectPProjectIdPromptExplorerRoute: ProjectPProjectIdPromptExplorerRoute,
    ProjectPProjectIdRankTrackingRoute:
      ProjectPProjectIdRankTrackingRouteWithChildren,
    ProjectPProjectIdSavedRoute: ProjectPProjectIdSavedRoute,
    ProjectPProjectIdIndexRoute: ProjectPProjectIdIndexRoute,
  }

const ProjectPProjectIdRouteRouteWithChildren =
  ProjectPProjectIdRouteRoute._addFileChildren(
    ProjectPProjectIdRouteRouteChildren,
  )

interface ProjectRouteRouteChildren {
  ProjectPProjectIdRouteRoute: typeof ProjectPProjectIdRouteRouteWithChildren
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectPProjectIdRouteRoute: ProjectPProjectIdRouteRouteWithChildren,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSubscribeRoute: typeof AuthenticatedSubscribeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSubscribeRoute: AuthenticatedSubscribeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAutumnSplatRoute: ApiAutumnSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
